In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sf-salaries/Salaries.csv
/kaggle/input/sf-salaries/database.sqlite

In [2]:
df = pd.read_csv('/kaggle/input/sf-salaries/Salaries.csv')

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (3,4,5,6,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

In [5]:
df['BasePay'].unique()

array([167411.18, 155966.02, 212739.13, ..., '6.04', '15.50',
       'Not Provided'], dtype=object)

In [15]:
df.drop(df[df['BasePay'] == 'Not Provided'].index, inplace = True)

In [16]:
df['BasePay'] = df['BasePay'].astype(float)

In [8]:
df['BasePay'].mean()

66325.4488404877

In [9]:
df['OvertimePay'] = df['OvertimePay'].astype(float)

In [10]:
df['OvertimePay'].max()

245131.88

In [11]:
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [12]:
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

Siapa yg mendapat bayaran paling besar? (Termasuk benefit)

In [ ]:
df[df['TotalPayBenefits'] == df['TotalPayBenefits'].max()]['EmployeeName']

In [ ]:
df[df['TotalPayBenefits'] == df['TotalPayBenefits'].min()]

cari rata-rata BasePay dari semua karyawan tiap tahun 2012-2013

In [ ]:
sal = df[(df['Year'] == 2012) | (df['Year'] == 2013)]
sal.groupby('Year').mean()['BasePay']

In [17]:
df.groupby('Year').mean()['BasePay']

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

Berapa jumlah unique titlejobs?

In [ ]:
len(df['JobTitle'].unique())

In [ ]:
5 pekerjaan teratas

In [ ]:
df['JobTitle'].value_counts().head()

jadikan data frame

In [ ]:
sal2 = df['JobTitle'].value_counts().head()
sal2 = sal2.to_frame()
sal2

Berapa byk pekerjaan yg di representasikan oleh satu org di tahun 2013

In [ ]:
sum(df[df['Year'] == 2013]['JobTitle'].value_counts() == 1)

Berapa jumlah org yg dalam JobTitle terdapat kata "Chief" di jobtitlenya ? (pake sum), coba tampilin siapa aja org yg punya nama Chief

In [ ]:
sum(df[df['JobTitle'] == 'Chief']['EmployeeName'].value_counts() == 1)

In [ ]:
sum(df[df['JobTitle'].str.contains("Chief", case=False)]["Id"].value_counts()==1)

Apa ada korelasi antara panjang string JobTitle dan Salary

In [ ]:
df["panjang_judul"] = df["JobTitle"].apply(len)

df[["TotalPayBenefits", 'panjang_judul']].corr()